# Generated by Django 4.1.4 on 2023-01-28 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=30, verbose_name='task')),
                ('start', models.DateTimeField(verbose_name='Начальная дата')),
                ('time', models.CharField(max_length=2, verbose_name='Время')),
            ],
        ),
    ]
