# Generated by Django 4.1.4 on 2022-12-29 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=30, verbose_name='task')),
                ('date', models.CharField(max_length=10, verbose_name='task')),
                ('time', models.CharField(max_length=2, verbose_name='task')),
            ],
        ),
    ]
